apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: serverops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      nodeSelector:
        kubernetes.io/hostname: worker

      containers:
        - name: mysql
          image: mysql:8.4

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mysql-secret

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: "1"
              memory: 1Gi

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
